### ISSUE TITLE
Bad link from the WordPress site on the About Us page

### ISSUE THREAD

**Issue by victorkane** [frontity-demos/tutorial-hello-frontity#2]
Great course! Great pedagogic method and content! Really exciting me about Frontity.

While working on [Use the `<html2react>` component](https://tutorial.frontity.org/part7-finishing-touches/use-the-html2react-component), I noticed that the About Us page contains a bad link from the (WordPress) server side. The format for posts is `/{year}/{slug}` (as in `/2016/small-and-picturesque-french-villages/`). However, there is one which omits the year: 

Where it says:

> Luis is an entrepreneur that enjoys travelling and reading. In his latest post, he writes about India and The [Taj Mahal](http://test.frontity.org/latest-trip-to-india/), one of the universally admired masterpieces of the world’s heritage.

The `year` is missing from the link.

Doesn't work with html2react conversion: `http://test.frontity.org/latest-trip-to-india/`

If I open the link in a separate tab, it gets redirected to `https://test.frontity.org/2016/latest-trip-to-india/` but it fails the `html2react` conversion (tricky!!). Because for internal routing it needs to be 'http://localhost:3000/2016/latest-trip-to-india/', but is actually `http://localhost:3000/latest-trip-to-india/`, so triggers a 404.

Hope I'm explaining this OK. Enjoying the tutorial immensely! Thanks!

**Comment by mburridge** [comment]
Good spot @victorkane. Thanks for pointing that out. I've fixed it.
